Welcome to Ubuntu 24.04 LTS (GNU/Linux 6.8.0-1008-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

 System information as of Thu Jun 13 08:04:18 UTC 2024

  System load:  0.01              Processes:             115
  Usage of /:   35.2% of 6.71GB   Users logged in:       1
  Memory usage: 25%               IPv4 address for enX0: 172.31.26.37
  Swap usage:   0%


Expanded Security Maintenance for Applications is not enabled.

77 updates can be applied immediately.
43 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status


Last login: Thu Jun 13 07:56:17 2024 from 18.206.107.29
ubuntu@ip-172-31-26-37:~$ cd tottime
ubuntu@ip-172-31-26-37:~/tottime$ ls
db.sqlite3  env  manage.py  staticfiles  tottime  tottimeapp  tottimekeypair.pem
ubuntu@ip-172-31-26-37:~/tottime$ git pull
Already up to date.
ubuntu@ip-172-31-26-37:~/tottime$ cd tottimeapp
ubuntu@ip-172-31-26-37:~/tottime/tottimeapp$ python3 manage.py makemigrations
python3: can't open file '/home/ubuntu/tottime/tottimeapp/manage.py': [Errno 2] No such file or directory
ubuntu@ip-172-31-26-37:~/tottime/tottimeapp$ ls
__init__.py  admin.py  forms.py    models.py  templates     tests.py  views.py
__pycache__  apps.py   migrations  static     templatetags  urls.py
ubuntu@ip-172-31-26-37:~/tottime/tottimeapp$ cd ..
ubuntu@ip-172-31-26-37:~/tottime$ python3 manage.py makemigrations
Traceback (most recent call last):
  File "/home/ubuntu/tottime/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/tottime/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/tottime/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
ubuntu@ip-172-31-26-37:~/tottime$ source env/bin/activate
(env) ubuntu@ip-172-31-26-37:~/tottime$ python3 manage.py makemigrations
Traceback (most recent call last):
  File "/home/ubuntu/tottime/manage.py", line 22, in <module>
    main()
  File "/home/ubuntu/tottime/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/core/management/base.py", line 454, in execute
    self.check()
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/tottime/tottime/urls.py", line 7, in <module>
    from tottimeapp import views
  File "/home/ubuntu/tottime/tottimeapp/views.py", line 11, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'
(env) ubuntu@ip-172-31-26-37:~/tottime$ pip install pytz
Collecting pytz
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 15.5 MB/s eta 0:00:00
Installing collected packages: pytz
Successfully installed pytz-2024.1
(env) ubuntu@ip-172-31-26-37:~/tottime$ python3 manage.py makemigrations
System check identified some issues:

WARNINGS:
?: (staticfiles.W004) The directory 'C:\Users\afick\OneDrive\Python Scripts\tottime\tottimeapp\static' in the STATICFILES_DIRS setting does not exist.
No changes detected
(env) ubuntu@ip-172-31-26-37:~/tottime$ git pull
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), 1.00 KiB | 1.00 MiB/s, done.
From https://github.com/aficklin12/tottime
   d912f9d..785de34  master     -> origin/master
Updating d912f9d..785de34
Fast-forward
 tottime/settings.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
(env) ubuntu@ip-172-31-26-37:~/tottime$ python3 manage.py makemigrations
No changes detected
(env) ubuntu@ip-172-31-26-37:~/tottime$ python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, tottimeapp
Running migrations:
  No migrations to apply.
(env) ubuntu@ip-172-31-26-37:~/tottime$ python3 manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings:

    /home/ubuntu/tottime/staticfiles

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Found another file with the destination path 'favicon.png'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'css/styles.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'assets/img/error-404-monochrome.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'assets/demo/chart-pie-demo.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'assets/demo/datatables-demo.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'assets/demo/chart-area-demo.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'assets/demo/chart-bar-demo.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/InternalEventBus.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/ColumnComponent.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/tabulator.js.map'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/Module.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/datatables-simple-demo.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/jquery_wrapper.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/CoreFeature.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/Helpers.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/optional.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/tabulator_esm.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/Cell.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/CellComponent.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/ColumnManager.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/tabulator.min.js.map'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/PseudoRow.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/Popup.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/InteractionMonitor.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/ComponentFunctionBinder.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/Row.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/OptionsList.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/options.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/Column.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/DataLoader.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/Alert.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/RowComponent.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/ExternalEventBus.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/tabulator_esm.js.map'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/tabulator_esm.min.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/TabulatorFull.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/DeprecationAdvisor.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/core.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/scripts.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/TableRegistry.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/tabulator.min.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/tabulator.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/ModuleBinder.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/RowManager.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/tabulator_esm.min.js.map'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/Renderer.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/FooterManager.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/defaults/options.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/renderers/BasicHorizontal.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/renderers/VirtualDomHorizontal.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/renderers/VirtualDomVertical.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'js/renderers/BasicVertical.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

126 static files copied to '/home/ubuntu/tottime/staticfiles', 52 unmodified.
(env) ubuntu@ip-172-31-26-37:~/tottime$ sudo ufw allow 8000
Rules updated
Rules updated (v6)
(env) ubuntu@ip-172-31-26-37:~/tottime$ python3 manage.py runserver
INFO:django.utils.autoreload:Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 13, 2024 - 04:15:42
Django version 5.0.6, using settings 'tottime.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

^C(env) ubuntu@ip-172-31-26-37:~/tottime$ 
(env) ubuntu@ip-172-31-26-37:~/tottime$ python3 manage.py runserver 0.0.0.0:8000
INFO:django.utils.autoreload:Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 13, 2024 - 04:16:55
Django version 5.0.6, using settings 'tottime.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[13/Jun/2024 04:24:00] code 400, message Bad request version ('G\x00#\x00\x00\x00-\x00\x02\x01\x01\x00+\x00\x07\x06ÚÚ\x03\x04\x03\x03\x00')
[13/Jun/2024 04:24:00] You're accessing the development server over HTTPS, but it only supports HTTP.
[13/Jun/2024 04:24:00] code 400, message Bad request version ('ÚsÿË')
[13/Jun/2024 04:24:00] You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '54.84.254.106:8000'. You may need to add '54.84.254.106' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.84.254.106:8000'. You may need to add '54.84.254.106' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /
[13/Jun/2024 04:24:00] "GET / HTTP/1.1" 400 143
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '54.84.254.106:8000'. You may need to add '54.84.254.106' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.84.254.106:8000'. You may need to add '54.84.254.106' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /favicon.ico
[13/Jun/2024 04:24:00] "GET /favicon.ico HTTP/1.1" 400 143
^C(env) ubuntu@ip-172-31-26-37:~/tottime$ git pull
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), 1019 bytes | 339.00 KiB/s, done.
From https://github.com/aficklin12/tottime
   785de34..82eb102  master     -> origin/master
Updating 785de34..82eb102
Fast-forward
 tottime/settings.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
(env) ubuntu@ip-172-31-26-37:~/tottime$ python3 manage.py runserver
INFO:django.utils.autoreload:Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 13, 2024 - 04:27:24
Django version 5.0.6, using settings 'tottime.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

^C(env) ubuntu@ip-172-31-26-37:~/tottime$ python3 manage.py runserver 0.0.0.0:8000
INFO:django.utils.autoreload:Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 13, 2024 - 04:27:40
Django version 5.0.6, using settings 'tottime.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[13/Jun/2024 04:27:43] code 400, message Bad request version ('\x00\x12\x00\x10\x04\x03\x08\x04\x04\x01\x05\x03\x08\x05\x05\x01\x08\x06\x06\x01\x00')
[13/Jun/2024 04:27:43] You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '54.84.254.106:8000'. You may need to add '54.84.254.106' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.84.254.106:8000'. You may need to add '54.84.254.106' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /
[13/Jun/2024 04:27:44] "GET / HTTP/1.1" 400 143
[13/Jun/2024 04:27:44] code 400, message Bad request version ('\x1a\x1a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06S')
[13/Jun/2024 04:27:44] You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '54.84.254.106:8000'. You may need to add '54.84.254.106' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.84.254.106:8000'. You may need to add '54.84.254.106' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /favicon.ico
[13/Jun/2024 04:27:44] "GET /favicon.ico HTTP/1.1" 400 143
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '54.84.254.106:8000'. You may need to add '54.84.254.106' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.84.254.106:8000'. You may need to add '54.84.254.106' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /
[13/Jun/2024 04:27:45] "GET / HTTP/1.1" 400 143
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '54.84.254.106:8000'. You may need to add '54.84.254.106' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/tottime/env/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.84.254.106:8000'. You may need to add '54.84.254.106' to ALLOWED_HOSTS.
WARNING:django.request:Bad Request: /favicon.ico
[13/Jun/2024 04:27:45] "GET /favicon.ico HTTP/1.1" 400 143
^C(env) ubuntu@ip-172-31-26-37:~/tottime$ git pull
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), 1.01 KiB | 343.00 KiB/s, done.
From https://github.com/aficklin12/tottime
   82eb102..78ad081  master     -> origin/master
Updating 82eb102..78ad081
Fast-forward
 tottime/settings.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
(env) ubuntu@ip-172-31-26-37:~/tottime$ python3 manage.py runserver 0.0.0.0:8000
Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 13, 2024 - 04:29:26
Django version 5.0.6, using settings 'tottime.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[13/Jun/2024 04:29:29] "GET / HTTP/1.1" 302 0
[13/Jun/2024 04:29:29] "GET /login/?next=/ HTTP/1.1" 200 3894
[13/Jun/2024 04:29:29] "GET /static/js/scripts.js HTTP/1.1" 200 3055
[13/Jun/2024 04:29:29] "GET /static/css/styles.css HTTP/1.1" 200 251130
[13/Jun/2024 04:29:29] "GET /static/favicon.png HTTP/1.1" 200 35473
[13/Jun/2024 04:29:38] "POST /login/?next=/ HTTP/1.1" 302 0
[13/Jun/2024 04:29:39] "GET /app/index.html HTTP/1.1" 200 29603
[13/Jun/2024 04:29:39] "GET /api/out-of-stock-items HTTP/1.1" 301 0
[13/Jun/2024 04:29:39] "GET /api/order-soon-items HTTP/1.1" 301 0
[13/Jun/2024 04:29:39] "GET /api/shopping-list HTTP/1.1" 200 68
[13/Jun/2024 04:29:39] "GET /api/out-of-stock-items/ HTTP/1.1" 200 76
[13/Jun/2024 04:29:39] "GET /api/order-soon-items/ HTTP/1.1" 200 247
[13/Jun/2024 04:29:39] "GET /api/out-of-stock-items/ HTTP/1.1" 200 76
[13/Jun/2024 04:29:39] "GET /api/order-soon-items/ HTTP/1.1" 200 247
[13/Jun/2024 04:29:43] "GET /app/index.html HTTP/1.1" 200 29603
[13/Jun/2024 04:29:43] "GET /api/shopping-list HTTP/1.1" 200 68
[13/Jun/2024 04:29:43] "GET /api/order-soon-items/ HTTP/1.1" 200 247
[13/Jun/2024 04:29:43] "GET /api/out-of-stock-items/ HTTP/1.1" 200 76
[13/Jun/2024 04:29:43] "GET /api/order-soon-items/ HTTP/1.1" 200 247
[13/Jun/2024 04:29:43] "GET /api/out-of-stock-items/ HTTP/1.1" 200 76
[13/Jun/2024 04:29:46] "GET /sign-in/ HTTP/1.1" 200 11156
[13/Jun/2024 04:29:46] "GET /api/out-of-stock-items/ HTTP/1.1" 200 76
[13/Jun/2024 04:29:46] "GET /api/order-soon-items/ HTTP/1.1" 200 247
[13/Jun/2024 04:29:48] "GET /daily-attendance/ HTTP/1.1" 200 7940
[13/Jun/2024 04:29:48] "GET /api/out-of-stock-items/ HTTP/1.1" 200 76
[13/Jun/2024 04:29:48] "GET /api/order-soon-items/ HTTP/1.1" 200 247
[13/Jun/2024 04:29:50] "GET /rosters/ HTTP/1.1" 200 14413
[13/Jun/2024 04:29:50] "GET /api/order-soon-items/ HTTP/1.1" 200 247
[13/Jun/2024 04:29:50] "GET /api/out-of-stock-items/ HTTP/1.1" 200 76
[13/Jun/2024 04:29:52] "GET /inventory/ HTTP/1.1" 200 171141
[13/Jun/2024 04:29:52] "GET /api/out-of-stock-items/ HTTP/1.1" 200 76
[13/Jun/2024 04:29:52] "GET /api/order-soon-items/ HTTP/1.1" 200 247
[13/Jun/2024 04:29:54] "GET /milk-count/ HTTP/1.1" 200 8863
[13/Jun/2024 04:29:54] "GET /api/out-of-stock-items/ HTTP/1.1" 200 76
[13/Jun/2024 04:29:54] "GET /api/order-soon-items/ HTTP/1.1" 200 247
[13/Jun/2024 04:29:57] "GET /classroom_options/ HTTP/1.1" 200 22262
[13/Jun/2024 04:29:57] "GET /api/out-of-stock-items/ HTTP/1.1" 200 76
[13/Jun/2024 04:29:57] "GET /api/order-soon-items/ HTTP/1.1" 200 247
[13/Jun/2024 04:36:31] code 400, message Bad request syntax ('JDWP-Handshake')
[13/Jun/2024 04:36:31] "JDWP-Handshake" 400 -
^C(env) ubuntu@ip-172-31-26-37:~/tottime$ 
(env) ubuntu@ip-172-31-26-37:~/tottime$ deactivate
ubuntu@ip-172-31-26-37:~/tottime$ sudo nano /etc/systemd/system/guniorn.socket
ubuntu@ip-172-31-26-37:~/tottime$ sudo nano /eetc/systemd/system/gunicorn.service
ubuntu@ip-172-31-26-37:~/tottime$ sudo nano /etc/sustemd/system/gunicorn.service
ubuntu@ip-172-31-26-37:~/tottime$ sudo nano /etc/systemd/system/gunicorn.service
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl start gunicorn.socket
Failed to start gunicorn.socket: Unit gunicorn.socket not found.
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl start gunicorn.socket
Failed to start gunicorn.socket: Unit gunicorn.socket not found.
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl daemon-reload
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl start gunicorn.socket
Failed to start gunicorn.socket: Unit gunicorn.socket not found.
ubuntu@ip-172-31-26-37:~/tottime$ sudo nano /etc/systemd/system/gunicorn.socket
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl daemon-reload
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl start gunicorn.socket
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl enable gunicorn.socket
Created symlink /etc/systemd/system/sockets.target.wants/gunicorn.socket → /etc/systemd/system/gunicorn.socket.
ubuntu@ip-172-31-26-37:~/tottime$ file /run/gunicorn.sock
/run/gunicorn.sock: socket
ubuntu@ip-172-31-26-37:~/tottime$ curl --unix-socket /run/gunicorn.sock localhost
curl: (56) Recv failure: Connection reset by peer
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl status gunicorn
× gunicorn.service - gunicorn daemon
     Loaded: loaded (/etc/systemd/system/gunicorn.service; disabled; preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-06-13 08:55:56 UTC; 24s ago
   Duration: 6ms
TriggeredBy: × gunicorn.socket
    Process: 6167 ExecStart=/home/unbuntu/tottime/env/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunic>
   Main PID: 6167 (code=exited, status=203/EXEC)
        CPU: 3ms

Jun 13 08:55:56 ip-172-31-26-37 systemd[1]: Started gunicorn.service - gunicorn daemon.
Jun 13 08:55:56 ip-172-31-26-37 systemd[1]: gunicorn.service: Main process exited, code=exited, status=203/EXEC
Jun 13 08:55:56 ip-172-31-26-37 systemd[1]: gunicorn.service: Failed with result 'exit-code'.
Jun 13 08:55:56 ip-172-31-26-37 systemd[1]: gunicorn.service: Start request repeated too quickly.
Jun 13 08:55:56 ip-172-31-26-37 systemd[1]: gunicorn.service: Failed with result 'exit-code'.
Jun 13 08:55:56 ip-172-31-26-37 systemd[1]: Failed to start gunicorn.service - gunicorn daemon.

ubuntu@ip-172-31-26-37:~/tottime$ sudo nano /etc/systemd/system/gunicorn.service
ubuntu@ip-172-31-26-37:~/tottime$ curl --unix-socket /run/gunicorn.sock localhost
curl: (7) Failed to connect to localhost port 80 after 0 ms: Couldn't connect to server
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl status gunicorn
Warning: The unit file, source configuration file or drop-ins of gunicorn.service changed on disk. Run 'systemctl daemon>
× gunicorn.service - gunicorn daemon
     Loaded: loaded (/etc/systemd/system/gunicorn.service; disabled; preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-06-13 08:55:56 UTC; 3min 34s ago
   Duration: 6ms
TriggeredBy: × gunicorn.socket
    Process: 6167 ExecStart=/home/unbuntu/tottime/env/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunic>
   Main PID: 6167 (code=exited, status=203/EXEC)
        CPU: 3ms

Jun 13 08:55:56 ip-172-31-26-37 systemd[1]: Started gunicorn.service - gunicorn daemon.
Jun 13 08:55:56 ip-172-31-26-37 systemd[1]: gunicorn.service: Main process exited, code=exited, status=203/EXEC
Jun 13 08:55:56 ip-172-31-26-37 systemd[1]: gunicorn.service: Failed with result 'exit-code'.
Jun 13 08:55:56 ip-172-31-26-37 systemd[1]: gunicorn.service: Start request repeated too quickly.
Jun 13 08:55:56 ip-172-31-26-37 systemd[1]: gunicorn.service: Failed with result 'exit-code'.
Jun 13 08:55:56 ip-172-31-26-37 systemd[1]: Failed to start gunicorn.service - gunicorn daemon.

ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl daemon-reload
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl restart gunicorn
ubuntu@ip-172-31-26-37:~/tottime$ curl --unix-socket /run/gunicorn.sock localhost
curl: (56) Recv failure: Connection reset by peer
ubuntu@ip-172-31-26-37:~/tottime$ ls -l /run/gunicorn.sock
srw-rw-rw- 1 root root 0 Jun 13 09:00 /run/gunicorn.sock
ubuntu@ip-172-31-26-37:~/tottime$ sudo journalctl -xe -u gunicorn
Jun 13 09:01:02 ip-172-31-26-37 systemd[1]: Started gunicorn.service - gunicorn daemon.
░░ Subject: A start job for unit gunicorn.service has finished successfully
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit gunicorn.service has finished successfully.
░░ 
░░ The job identifier is 5460.
Jun 13 09:01:02 ip-172-31-26-37 (gunicorn)[6257]: gunicorn.service: Changing to the requested working directory failed: >
Jun 13 09:01:02 ip-172-31-26-37 systemd[1]: gunicorn.service: Main process exited, code=exited, status=200/CHDIR
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStart= process belonging to unit gunicorn.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 200.
Jun 13 09:01:02 ip-172-31-26-37 systemd[1]: gunicorn.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit gunicorn.service has entered the 'failed' state with result 'exit-code'.
Jun 13 09:01:02 ip-172-31-26-37 systemd[1]: Started gunicorn.service - gunicorn daemon.
░░ Subject: A start job for unit gunicorn.service has finished successfully
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit gunicorn.service has finished successfully.
░░ 
░░ The job identifier is 5569.
Jun 13 09:01:02 ip-172-31-26-37 (gunicorn)[6259]: gunicorn.service: Changing to the requested working directory failed: >
Jun 13 09:01:02 ip-172-31-26-37 systemd[1]: gunicorn.service: Main process exited, code=exited, status=200/CHDIR
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStart= process belonging to unit gunicorn.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 200.
Jun 13 09:01:02 ip-172-31-26-37 systemd[1]: gunicorn.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit gunicorn.service has entered the 'failed' state with result 'exit-code'.
Jun 13 09:01:02 ip-172-31-26-37 systemd[1]: gunicorn.service: Start request repeated too quickly.
Jun 13 09:01:02 ip-172-31-26-37 systemd[1]: gunicorn.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit gunicorn.service has entered the 'failed' state with result 'exit-code'.
Jun 13 09:01:02 ip-172-31-26-37 systemd[1]: Failed to start gunicorn.service - gunicorn daemon.
░░ Subject: A start job for unit gunicorn.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit gunicorn.service has finished with a failure.
░░ 
░░ The job identifier is 5678 and the job result is failed.
lines 218-278/278 (END)
ubuntu@ip-172-31-26-37:~/tottime$ sudo nano /etc/systemd/system/gunicorn.service
ubuntu@ip-172-31-26-37:~/tottime$ ^C
ubuntu@ip-172-31-26-37:~/tottime$ sudo nano /etc/systemd/system/gunicorn.service
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl daemon-reload
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl restart gunicorn
ubuntu@ip-172-31-26-37:~/tottime$ curl --unix-socket /run/gunicorn.sock localhost
curl: (56) Recv failure: Connection reset by peer
ubuntu@ip-172-31-26-37:~/tottime$ sudo nano /etc/systemd/system/gunicorn.service
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl daemon-reload
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl restart gunicorn
ubuntu@ip-172-31-26-37:~/tottime$ curl --unix-socket /run/gunicorn.sock localhost
ubuntu@ip-172-31-26-37:~/tottime$ curl --unix-socket /run/gunicorn.sock localhost
ubuntu@ip-172-31-26-37:~/tottime$ sudo nano /etc/systemd/system/gunicorn.service
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl daemon-reload
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl restart gunicorn
ubuntu@ip-172-31-26-37:~/tottime$ curl --unix-socket /run/gunicorn.sock localhost
curl: (56) Recv failure: Connection reset by peer
ubuntu@ip-172-31-26-37:~/tottime$ sudo nano /etc/systemd/system/gunicorn.service
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl daemon-reload
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl restart gunicorn
ubuntu@ip-172-31-26-37:~/tottime$ curl --unix-socket /run/gunicorn.sock localhost
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl status gunicorn
● gunicorn.service - gunicorn daemon
     Loaded: loaded (/etc/systemd/system/gunicorn.service; disabled; preset: enabled)
     Active: active (running) since Thu 2024-06-13 09:17:02 UTC; 43s ago
TriggeredBy: ● gunicorn.socket
   Main PID: 6587 (gunicorn)
      Tasks: 4 (limit: 1130)
     Memory: 96.5M (peak: 96.7M)
        CPU: 890ms
     CGroup: /system.slice/gunicorn.service
             ├─6587 /home/ubuntu/tottime/env/bin/python /home/ubuntu/tottime/env/bin/gunicorn --access-logfile - --worke>
             ├─6588 /home/ubuntu/tottime/env/bin/python /home/ubuntu/tottime/env/bin/gunicorn --access-logfile - --worke>
             ├─6589 /home/ubuntu/tottime/env/bin/python /home/ubuntu/tottime/env/bin/gunicorn --access-logfile - --worke>
             └─6590 /home/ubuntu/tottime/env/bin/python /home/ubuntu/tottime/env/bin/gunicorn --access-logfile - --worke>

Jun 13 09:17:02 ip-172-31-26-37 systemd[1]: Started gunicorn.service - gunicorn daemon.
Jun 13 09:17:02 ip-172-31-26-37 gunicorn[6587]: [2024-06-13 09:17:02 +0000] [6587] [INFO] Starting gunicorn 22.0.0
Jun 13 09:17:02 ip-172-31-26-37 gunicorn[6587]: [2024-06-13 09:17:02 +0000] [6587] [INFO] Listening at: unix:/run/gunico>
Jun 13 09:17:02 ip-172-31-26-37 gunicorn[6587]: [2024-06-13 09:17:02 +0000] [6587] [INFO] Using worker: sync
Jun 13 09:17:02 ip-172-31-26-37 gunicorn[6588]: [2024-06-13 09:17:02 +0000] [6588] [INFO] Booting worker with pid: 6588
Jun 13 09:17:02 ip-172-31-26-37 gunicorn[6589]: [2024-06-13 09:17:02 +0000] [6589] [INFO] Booting worker with pid: 6589
Jun 13 09:17:02 ip-172-31-26-37 gunicorn[6590]: [2024-06-13 09:17:02 +0000] [6590] [INFO] Booting worker with pid: 6590
Jun 13 09:17:08 ip-172-31-26-37 gunicorn[6589]:  - - [13/Jun/2024:05:17:08 -0400] "GET / HTTP/1.1" 302 0 "-" "curl/8.5.0"

ubuntu@ip-172-31-26-37:~/tottime$ sudo nano /ect/nginx/sites-available/djangopro
ubuntu@ip-172-31-26-37:~/tottime$ sudo nano /etc/nginx/sites-available/djangopro
ubuntu@ip-172-31-26-37:~/tottime$ sudo ln -s /ect/nginx/sites-available/djangopro
ubuntu@ip-172-31-26-37:~/tottime$ sudo ln -s /ect/nginx/sites-available/djangopro /etc/nginx/sites-enabled
ubuntu@ip-172-31-26-37:~/tottime$ sudo nginx -t
2024/06/13 09:27:19 [emerg] 6634#6634: open() "/etc/nginx/sites-enabled/djangopro" failed (2: No such file or directory) in /etc/nginx/nginx.conf:60
nginx: configuration file /etc/nginx/nginx.conf test failed
ubuntu@ip-172-31-26-37:~/tottime$ sudo ln -s /etc/nginx/sites-available/djangopro /etc/nginx/sites-enabled/djangopro
ln: failed to create symbolic link '/etc/nginx/sites-enabled/djangopro': File exists
ubuntu@ip-172-31-26-37:~/tottime$ sudo nginx -t
2024/06/13 09:27:57 [emerg] 6641#6641: open() "/etc/nginx/sites-enabled/djangopro" failed (2: No such file or directory) in /etc/nginx/nginx.conf:60
nginx: configuration file /etc/nginx/nginx.conf test failed
ubuntu@ip-172-31-26-37:~/tottime$ sudo rm /etc/nginx/sites-enabled/djangopro
ubuntu@ip-172-31-26-37:~/tottime$ sudo rm /etc/nginx/sites-enabled/djangopro
rm: cannot remove '/etc/nginx/sites-enabled/djangopro': No such file or directory
ubuntu@ip-172-31-26-37:~/tottime$ sudo ln -s /etc/nginx/sites-available/djangopro /etc/nginx/sites-enabled/djangopro
ubuntu@ip-172-31-26-37:~/tottime$ sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl restart nginx
ubuntu@ip-172-31-26-37:~/tottime$ sudo ufw delete allow 8000
Rules updated
Rules updated (v6)
ubuntu@ip-172-31-26-37:~/tottime$ sudo ufw allow 'Nginx Full'
Rules updated
Rules updated (v6)
ubuntu@ip-172-31-26-37:~/tottime$ sudo nano /etc/nginx/sites-available/djangopro
ubuntu@ip-172-31-26-37:~/tottime$ sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
ubuntu@ip-172-31-26-37:~/tottime$ sudo systemctl reload nginx
ubuntu@ip-172-31-26-37:~/tottime$ 
